#####################################################
#                                                   #
#  Select Input - Harmony                           #
#                                                   #
#####################################################
- alias: Harmony
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.harmony
    from: 'Select Input'
  action:
    - service: remote.turn_on
      entity_id: remote.livingroom
      data_template:
        activity: >
          {% if is_state("input_select.harmony", "Entertain") %}
            24508879
          {% elif is_state("input_select.harmony", "Netflix & Chill") %}
            24284482
          {% else %}
          {% endif %}
    - service: input_select.select_option
      entity_id: input_select.harmony
      data_template:
        option: "Select Input"
#####################################################
#                                                   #
#  Harmony Off                        #
#                                                   #
#####################################################
- alias: Harmony Off
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.harmony
    to: 'Power Off'
  action:
    - service: remote.turn_off
      entity_id: remote.livingroom
    - service: input_select.select_option
      entity_id: input_select.harmony
      data_template:
        option: "Select Input"
#####################################################
#                                                   #
#  LR Motion after bed time                         #
#                                                   #
#####################################################
- alias: LR Lights on Movement
  trigger:
    platform: state
    entity_id: sensor.lr_motion
    to: '1'
  condition:
    condition: time
    after: '00:00:00'
    before: '07:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.google_lamp
- alias: LR off
  trigger:
    platform: state
    entity_id: sensor.lr_motion
    to: '0'
    for:
      minutes: 5
  condition:
    condition: time
    after: '00:00:00'
    before: '07:00:00'
  action:
     service: light.google_lamp
     entity_id: switch.livingroom_lamp
#####################################################
#                                                   #
#  Home Assistant Startup Notification              #
#                                                   #
#####################################################
- alias: HASS Startup Notification
  trigger:
    platform: event
    event_type: homeassistant_start
  action:
    service: notify.notify
    data:
      message: 'Home assistant started'

#####################################################
#                                                   #
#  Home Assistant Update Notification               #
#                                                   #
#####################################################
- alias: HASS Update Notification
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    - service: notify.notify
      data:
        message: 'Home Assistant Update Available'
    - service: persistent_notification.create
      data:
        title: "Home Assistant Update Available"
        message: "Home Assistant {{ states('updater.updater') }} is available. - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
        notification_id: "update_available"
#####################################################
#                                                   #
#              Temp is too hot                      #
#                                                   #
#####################################################
- alias: High Temp in Living Room
  hide_entity: False
  trigger:
    platform: numeric_state
    entity_id: sensor.lr_temperature
    above: 74
  action:
    service: notify.notify
    data:
      message: "It's too hot. You should adjust the thermostat."
#####################################################
#                                                   #
#              Temp is too cold                     #
#                                                   #
#####################################################
- alias: Low Temp in Living Room
  hide_entity: False
  trigger:
    platform: numeric_state
    entity_id: sensor.lr_temperature
    below: 66
  action:
    service: notify.notify
    data:
      message: "It's getting cold. You shoud adjust the thermostat."
#####################################################
#                                                   #
#              Bri is home                     #
#                                                   #
#####################################################
- alias: Bri arrives home
  hide_entity: False
  trigger:
    platform: state
    entity_id: device_tracker.galaxy_bri
    to: 'home'
  condition:
    condition: time
    after: '17:00:00'
    before: '18:00:00'
  action:
    - service: script.turn_on
      entity_id: script.bri_home
#####################################################
#                                                   #
#              Andrew is home                     #
#                                                   #
#####################################################
- alias: Andrew arrives home
  hide_entity: False
  trigger:
    platform: state
    entity_id: device_tracker.pixel_andrew
    to: 'home'
  condition:
    condition: time
    after: '18:00:00'
    before: '20:00:00'
  action:
    - service: script.turn_on
      entity_id: script.andrew_home
###############################################################################
# Turn indoor lights on 60 minutes before sunset
###############################################################################
- alias: Indoor Lights ON before Sunset
  trigger:
    platform: sun
    event: sunset
    offset: '-01:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.google_lamp
        transition: 55
        rgb_color: [245,250,246]
        brightness: 254
        color_temp: 250
    - service: light.turn_on
      data:
        entity_id: light.couch_left
        transition: 55
        rgb_color: [245,250,246]
        brightness: 254
        color_temp: 250
    - service: light.turn_on
      data:
        entity_id: light.couch_right
        transition: 55
        rgb_color: [245,250,246]
        brightness: 254
        color_temp: 250
#####################################################
#                                                   #
#              Washing Machine Completes Wash                     #
#                                                   #
#####################################################
- alias: Washer Completes Wash
  trigger:
    platform: state
    entity_id: input_select.washing_machine_status
    to: 'Running'
    for:
      minutes: 70
  action:
    - service: notify.notify
      data:
        message: "The washer has completed its cycle. Please change the laundry."
    - service: input_select.select_option
      data:
        entity_id: input_select.washing_machine_status
        option: 'Clean'
#####################################################
#                                                   #
#              Dryer Completes Cycle                     #
#                                                   #
#####################################################
- alias: Dryer Completes Cycle
  trigger:
    platform: state
    entity_id: input_select.dryer_status
    to: 'Running'
    for:
      minutes: 60
  action:
    - service: notify.notify
      data:
        message: "The dryer has completed its cycle. Please remove the laundry."
    - service: input_select.select_option
      data:
        entity_id: input_select.dryer_status
        option: 'Dried'
#####################################################
#                                                   #
#              Dishwasher Starts Cycle                    #
#                                                   #
#####################################################
- alias: Dishwasher Starts Cycle
  trigger:
    platform: state
    entity_id: input_select.dishwasher_status
    to: 'Running'
    for:
      minutes: 30
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.dishwasher_status
      option: 'Drying'
#####################################################
#                                                   #
#              Dishwasher Completes Cycle                     #
#                                                   #
#####################################################
- alias: Dishwasher Completes Cycle
  trigger:
    platform: state
    entity_id: input_select.dishwasher_status
    to: 'Drying'
    for:
      minutes: 30
  action:
    - service: notify.notify
      data:
        message: "The dishwasher has completed its cycle. Time to put away the dishes!"
    - service: input_select.select_option
      data:
        entity_id: input_select.dishwasher_status
        option: 'Clean'
#####################################################
#                                                   #
#              Notify if any lights are left on                     #
#                                                   #
#####################################################
#- alias: Notify if Light is on
#  trigger:
#    platform: state
#    state: 'on'
#    entity_id: group.livingroomlights
#  condition:
#    condition: time
#    after: '00:00:00'
#  action:
#    - service: notify.notify
#      data:
#        message: 'You left {% for state in states.group if state.state == 'on'-%}  {%- if loop.first %}the {% elif loop.last %} and the {% else %}, the {% endif -%}  {{ state.name | lower }} light {{state.state}}{%- endfor -%}.'
    
