### CONFIGURATION ###

## GENERAL ##
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 203
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
########## INCLUDE ##########
########## Devices ##########
switch: !include devices/switches.yaml
sensor: !include devices/sensors.yaml
media_player: !include devices/media_players.yaml
input_select: !include input_select.yaml
tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
remote:
  - platform: harmony
    name: livingroom
    host: 10.0.0.105
    port: 5222
    scan_interval: 45
########## Web Links ##########
weblink: !include web_links.yaml
########## Groups ##########
group: !include groups.yaml
########## Automation ##########
automation: !include automation.yaml
script: !include script.yaml
########## ACTIVATE ##########
history: !include history.yaml
#discovery:
updater:
frontend:
sun:
########## HTTP ##########
http:
  api_password: !secret api_password
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  cors_allowed_origins:
    - https://google.com
    - https://home-assistant.io
  use_x_forwarded_for: True
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.0.0/24
    - 2001:DB8:ABCD::/48
  ip_ban_enabled: True
  login_attempts_threshold: 5
 ########## IFTTT ##########
ifttt:
  key: !secret ifttt_key
########## MQTT Broker ##########
mqtt:
  broker: 10.0.0.106
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_un
  password: !secret mqtt_pw
device_tracker:
  - platform: nmap_tracker
    hosts:
     - !secret dev_tracker_bri
     - !secret dev_tracker_andrew
    consider_home: 180
    home_interval: 10
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: True
########## ZONES ##########
zone: !include zones.yaml
########## RECORDER ##########
recorder:
  purge_days: 3
########## PUSHBULLET NOTIFY ##########
notify:
  platform: pushbullet
  api_key: !secret pushbullet_key
########## EMULATED HUE ##########
emulated_hue:
  host_ip: 10.0.0.106
  listen_port: 80
  off_maps_to_on_domains:
    - script
    - scene
  expose_by_default: true
  exposed_domains:
    - light
    - switch
    - scene
    - script
    - media_player
    - group
########## CONFIG TAB ##########
config:
########## TRADFRI ##########
tradfri:
  host: 10.0.0.101
  api_key: !secret tradfri_key

